/* istanbul ignore file */
export const dataTestIds = {
  components: {
    spaceContainer: 'space-container',
    customIconButtonAndText: {
      iconButton: 'custom-icon-button',
      text: 'custom-text',
    },
    infoCard: {
      container: 'info-card-container',
      icon: 'info-card-icon',
      title: 'info-card-title',
      text: 'info-card-text',
    },
    appHeader: {
      container: 'app-header-container',
      logo: 'app-header-logo',
      accountButton: 'app-header-account-button',
      menu: 'app-header-menu',
      menuItemAccount: 'app-header-menu-item-account',
      menuItemLogout: 'app-header-menu-item-logout',
    },
    truncatedText: {
      textElement: 'truncated-text-element',
    },
    dateNavigator: {
      previousButton: 'date-navigator-previous-button',
      nextButton: 'date-navigator-next-button',
      dateDisplay: 'date-navigator-date-display',
      editButton: 'date-navigator-edit-button',
    },
    mealGenerator: {
      container: 'meal-generator-container',
      tab: (mealType: string) => `meal-generator-tab-${mealType}`,
      queryInput: 'meal-generator-query-input',
      minCaloriesInput: 'meal-generator-min-calories-input',
      maxCaloriesInput: 'meal-generator-max-calories-input',
      minSugarInput: 'meal-generator-min-sugar-input',
      maxSugarInput: 'meal-generator-max-sugar-input',
      generateButton: 'meal-generator-generate-button',
      loadingIndicator: 'meal-generator-loading-indicator',
    },
    mealSlot: {
      container: (index: number) => `meal-slot-${index}`,
      addButton: (index: number) => `meal-slot-add-button-${index}`,
      removeButton: (index: number) => `meal-slot-remove-button-${index}`,
      emptyText: (index: number) => `meal-slot-empty-text-${index}`,
      recipeTitle: (index: number) => `meal-slot-recipe-title-${index}`,
      recipeImage: (index: number) => `meal-slot-recipe-image-${index}`,
    },
    nutritionStats: {
      container: 'nutrition-stats-container',
      tabs: 'nutrition-stats-tabs',
      dailyTab: 'nutrition-stats-daily-tab',
      weeklyTab: 'nutrition-stats-weekly-tab',
      content: 'nutrition-stats-content',
      loadingIndicator: 'nutrition-stats-loading-indicator',
      noData: 'nutrition-stats-no-data',
      goToMealPlannerButton: 'nutrition-stats-go-to-meal-planner-button',
      averageCalories: 'nutrition-stats-average-calories',
      chart: 'nutrition-stats-chart',
    },
    recipeCard: {
      container: 'recipe-card-container',
      image: 'recipe-card-image',
      placeholderImage: 'recipe-card-placeholder-image',
      title: 'recipe-card-title',
      description: 'recipe-card-description',
      seeMoreButton: 'recipe-card-see-more-button',
      addButton: 'recipe-card-add-button',
      addIcon: 'recipe-card-add-icon',
      removeIcon: 'recipe-card-remove-icon',
    },
  },
};
